### PR TITLE
Generate failure line number at Example data line rather than the Scenario Outline line

### LINKED ISSUE #52: Generate line number at Example data line of the failing case rather than the Scenario Outline line
```Cucumber
1 Scenario Outline: This is a scenario outline 
2    When I start the test
3    And I use the <testData> for <testCase>
4
5     Examples:
6     | testCase           | testData    |
7     | case1              | value1      |
8     | case2              | value2      |
9     | case3              | value3      |
```

Currently, for the above Scenario Outline, if the test scenario with say, the second row of Example data fails, then rerun service will generate the rerun scenaroisLineNumber using the line number of the whole Scenario Outline (line number 1 here) instead of the line number of the Example data of the failing scenario (line number 8 here). Consequently, all three scenarios will be rerun instead of the only failing scenario.

It would be more efficient if we could improve this behaviour.

### PR DESCRIPTION
**Pull request by wenzhhu**
Resolves #52

### CODE REVIEW

**Comment by esaari** [comment]
This looks good, is it possible you could `cherry-pick` this change into `main` so we can get it into the next mainline release or open an entirely new PR?

**Comment by wenzhhu** [comment]
> This looks good, is it possible you could `cherry-pick` this change into `main` so we can get it into the next mainline release or open an entirely new PR?

@esaari I don't think we can easily `cherry-pick` the change into `main` because v8 is type-script based now. And I need some time to review my TS knowledge :)

I will create a new PR once I'm ready which I will try to be in less than 3 weeks.

**Comment by mikesalvia** [comment]
@esaari GitHub actions are not configured for `v7` I will do that now.

**Comment by mikesalvia** [comment]
https://github.com/webdriverio-community/wdio-rerun-service/pull/54 This should do it but I think I will need to apply to v7 as well. I will do that now.

**Comment by mikesalvia** [comment]
I enabled the GitHub actions for the branches you are merging too but it didn't start automagically on your open PR. Standby.

**Comment by mikesalvia** [comment]
@wenzhhu There we go! Looks like it is cooking now.

**Review by mikesalvia — APPROVED** [review]
@wenzhhu @esaari @christian-bromann Fundamentally, I don't have any issues with this PR. I, however, want to hold off on merging this for the moment to have @christian-bromann let us know the proper way to support both LTS and stable from within a service.

**Comment by esaari** [comment]
@mikesalvia Just a FYI, WDIO v6 has been officially deprecated. We will only need to support v7 until October of this year: https://webdriver.io/versions

We can probably delete the v6 branch and just leave `v7` and `main`

**Comment by wenzhhu** [comment]
Hi guys, can we proceed with this PR?

**Pull request merged**
