### PR TITLE
Fix rerun script for Windows

### LINKED ISSUE #30: rerun script is invalid on Windows
wdio: 7.0.7
rerun: 1.7.2

Hello,

The generated rerun.bat file is not a valid command for Windows ( at least on my machine)

DISABLE_RERUN=true node_modules/.bin/wdio run --spec=C:/Apps/test/features/01_test.feature:5

DISABLE_RERUN=true. this is not recognised

should be set DISABLE_RERUN= true if it is an env variable

Working line would be:

set DISABLE_RERUN=true && npx wide run ./wdio.conf.ts --spec=C:/Apps/test/features/01_test.feature:5

Do I miss something ?

Thanks

Attila

### PR DESCRIPTION
**Pull request by SCG82**
Fixes #30

- use `npx wdio` instead of `node_modules/.bin/wdio`
- make script executable (755)

Based on #43, see https://github.com/SCG82/wdio-rerun-service/pull/2 to view the diff.

Merge #42, then #43 before merging this PR,

### CODE REVIEW

**Comment by christian-bromann** [comment]
@esaari @mikesalvia comments?

**Comment by christian-bromann** [comment]
It seems like this PR contains same changes as in #42

**Comment by SCG82** [comment]
> It seems like this PR contains same changes as in #42

I didn't rebase this onto master to avoid conflicts, and because some of the changes are to the E2E test I added in #43. Once #42 & #43 are merged in, this PR will look like https://github.com/SCG82/wdio-rerun-service/pull/2.

**Comment by SCG82** [comment]
Closing in lieu of #47

**Pull request closed without merging**
