### PR TITLE
Refactor and improve tests

### LINKED ISSUE #36: Transition package from CJS to ESM
As part of the [v8 effort](https://github.com/webdriverio/webdriverio/issues?q=is%3Aopen+is%3Aissue+milestone%3Av8) we are currently [migrating over to ESM](https://github.com/webdriverio/webdriverio/issues/8306) as many packages will stop support CJS in the future. This means we have to transition all plugins to ESM as well, ideally with continuous support for CJS.

### PR DESCRIPTION
**Pull request by SCG82**
Resolves #36

- ~~Fix~~ Remove directory exists check: https://github.com/webdriverio-community/wdio-rerun-service/blob/main/src/index.js#L71

Based on #42, see https://github.com/SCG82/wdio-rerun-service/pull/1 to view the diff.

Merge #42 before merging this PR.

### CODE REVIEW

**Comment by SCG82** [comment]
> Same here, it seems like similar PR as to #42 and #44, any chance you can chain them?

Doesn't look like that's possible unless I can push these branches to this repository.

**Comment by esaari** [comment]
@SCG82 I merged #42, can you fix these conflicts? I will merge the remaining PRs then do the release.

**Comment by christian-bromann** [comment]
I also added you (@SCG82) to the org, so feel free to go ahead and just merge directly into `main`. Thanks for everything!

**Comment by SCG82** [comment]
closing in lieu of #46

**Pull request closed without merging**
