### PR TITLE
Ensure element contains scenario inside filter function

### PR DESCRIPTION
**Pull request by yopasa94**
Related to issue https://github.com/webdriverio-community/wdio-rerun-service/issues/21

### CODE REVIEW

**Comment by yopasa94** [comment]
Test failed after updating world object with background element
image

After change
image

**Review by christian-bromann — APPROVED** [review]
Awesome, thanks 👍

**Comment by christian-bromann** [comment]
@yopasa94 can you check why some of the builds are failing?

**Comment by yopasa94** [comment]
> @yopasa94 can you check why some of the builds are failing?

There are some limitations to build/run actions on fork branch 

Please take a look into this -> https://github.community/t/github-actions-are-severely-limited-on-prs/18179#M9249

_However, for security reasons, the team at GitHub has decided to issue a GITHUB_TOKEN that has read-only access to the entire GitHub repository when the action is run from a fork._

**Comment by mikesalvia** [comment]
I am going to merge this in if builds start failing we can revert.

**Pull request merged**
